### ISSUE TITLE
jnius fails with multiple openJDK versions

### ISSUE THREAD

**Issue by recski** [dlt-rilmta/e-magyar-tsv#1]
Tried installing based on the README, but 

```
Traceback (most recent call last):
  File "./emTagREST.py", line 12, in <module>
    prog = tagger(*args, **kwargs)
  File "/home/recski/tools/e-magyar-tsv/purepospy/purepospy.py", line 66, in __init__
    self._autoclass = import_pyjnius(PurePOS.class_path)
  File "/home/recski/tools/e-magyar-tsv/purepospy/purepospy.py", line 34, in import_pyjnius
    from jnius import autoclass
  File "/home/recski/miniconda3/envs/sandbox/lib/python3.7/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/home/recski/miniconda3/envs/sandbox/lib/python3.7/site-packages/jnius/reflect.py", line 15, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/recski/miniconda3/envs/sandbox/lib/python3.7/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 111, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 161, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Makefile:53: recipe for target 'test-morph-tag' failed
make: *** [test-morph-tag] Error 1

```
My openjdk-11 installation has `libjvm.so` at a different location, so I tried creating a symlink at the path that seems to be hardwired into jnius, but that just delayed the error until a bit later:

```
string	anas	lemma	hfstana
Compiling model...Traceback (most recent call last):
  File "./emTagREST.py", line 21, in <module>
    create_cli_app(prog, sys.stdin, sys.stdout)
  File "/home/recski/tools/e-magyar-tsv/TSVRESTTools/common.py", line 19, in create_cli_app
    output_stream.writelines(process(input_stream, prog))
  File "/home/recski/tools/e-magyar-tsv/TSVRESTTools/tsvhandler.py", line 40, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/home/recski/tools/e-magyar-tsv/purepospy/purepospy.py", line 221, in process_sentence
    for tok, (_, lemma, hfstana) in zip(sen, self.tag_sentence(sent)):
  File "/home/recski/tools/e-magyar-tsv/purepospy/purepospy.py", line 168, in tag_sentence
    read_mod = serializer().readModelEx(self._model_jfile)
  File "jnius/jnius_export_class.pxi", line 733, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 899, in jnius.JavaMethod.call_staticmethod
  File "jnius/jnius_utils.pxi", line 93, in jnius.check_exception
jnius.JavaException: JVM exception occurred: invalid stream header: 76657273
```

Finally, I also tried downgrading my openjdk from 11 to 8 and then symlinking default-java to the openjdk-8 installation, but got the same error again (invalid stream header)

**Comment by dlazesz** [comment]
Please check the following:

- Is your JAVA_HOME env variable set properly? The heuristic is the following:

        # Set JAVA_HOME for this session
        try:
            os.environ['JAVA_HOME']
        except KeyError:
            os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-8-openjdk-amd64/'  # This is known to work on Ubuntu and Debian

This has nothing to do with '/usr/lib/jvm/default-java/jre/lib/amd64/' as in your error message.

- Please verify if e.g. the supplied binary version of PurePOS is running standalone without Python, because it seems to be a problem with your JAVA installation.

         java -jar purepospy/purepos/purepos-2.1-dev.one-jar.jar
 
- Try loading PyJNIus in the interactive Python terminal to verify it is working.

         from jnius import autoclass
         autoclass('java.lang.String')

If everything above works fine, but emTSV still not working, then please supply your distribution and environment details for us to further investigate the issue.

**Comment by recski** [comment]
On Thu, Nov 8, 2018 at 9:45 PM Indig Balázs <notifications@github.com>
wrote:

> Please check the following:
>
>    -
>
>    Is your JAVA_HOME env variable set properly? The heuristic is the
>    following:
>
>      # Set JAVA_HOME for this session
>      try:
>          os.environ['JAVA_HOME']
>      except KeyError:
>          os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-8-openjdk-amd64/'  # This is known to work on Ubuntu and Debian
>
>
>
my JAVA_HOME is `/usr/lib/jvm/default-java/`, which is a symlink to
`/usr/lib/jvm/java-11-openjdk-amd64`. I can relink to an openjdk-8
installation, but that will cause the "iinvalid stream header" error (see
prev. post).


>
>    -
>
>    Please verify if e.g. the supplied binary version of PurePOS is
>    running standalone without Python, because it seems to be a problem with
>    your JAVA installation.
>
>       java -jar purepospy/purepos/purepos-2.1-dev.one-jar.jar
>
>
>
Seems to work:
```
Error: Option "-m (--model)" is required

Usage: java -jar <purepos.jar> [options...] arguments...
(...)
```


>
>    -
>
>    Try loading PyJNIus in the interactive Python terminal to verify it is
>    working.
>
>       from jnius import autoclass
>       autoclass('java.lang.String')
>
>
> This also seems to work fine
```
>>> from jnius import autoclass
>>> autoclass('java.lang.String')
<class 'jnius.reflect.java.lang.String'>
```

If everything above works fine, but emTSV still not working, then please
> supply your distribution and environment details for us to further
> investigate the issue.
>
Ubunut 18.04, Linux 4.15.0-38-generic
Python 3.7.1
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by dlazesz** [comment]
I tried to reproduce the mentioned behaviour. The following commands led me to the first error with 'libjvm.so':

```bash
sudo debootstrap bionic bionic_chroot
cd bionic_chroot
sudo mount -t proc proc proc/
sudo mount -t sysfs sys sys/
sudo mount -o bind /dev dev/
sudo chroot .
apt install curl
sed -i 's/main$/main universe/' /etc/apt/sources.list
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt install git python3 python3-pip hfst git-lfs openjdk-11-jdk-headless
adduser --disabled-password --gecos "" testuser
locale-gen hu_HU.UTF-8
update-locale LANG=hu_HU.UTF-8
su - testuser
git-lfs install
git clone --recurse-submodules https://github.com/dlt-rilmta/e-magyar-tsv
exit
pip3 install Cython
pip3 install -r /home/testuser/e-magyar-tsv/emmorphpy/requirements.txt
pip3 install -r /home/testuser/e-magyar-tsv/purepospy/requirements.txt
pip3 install -r /home/testuser/e-magyar-tsv/emdeppy/requirements.txt
pip3 install -r /home/testuser/e-magyar-tsv/HunTag3/requirements.txt
su - testuser
cd e-magyar-tsv/
time make test-morph-tag > out.input.morph-tag
```

I've realized that, the actual file is in: /usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so
PyJNIus searches it in: /usr/lib/jvm/java-11-openjdk-amd64/ **jre/** lib/server/libjvm.so

I've found no way to circumvent this path problem for openjdk-11. I guess PyJNIus do not support openjdk-11 yet. [See the code causing this behaviour.](https://github.com/kivy/pyjnius/blob/91780187093f06b8e6bf1f09d9a623b6cf4b86d3/setup.py#L182) But there is also openjdk-8 in the repositories and installing `openjdk-8-jdk-headless` makes the test up and running...

__Conclusion__: 

- Use openjdk-8 instead of 11 (TODO fix documentation)
- Setting an UTF-8 locale is a must!

Please test the above to verify how your enviroment differs, and what needs to be fixed.

**Comment by recski** [comment]
I already tried downgrading to openjdk-8, which lead to another error,
please see my first post for details

**Comment by dlazesz** [comment]
You are using some wierd non-standard setup, which we probably not support.
I created a python3.7 virtualenv on Ubuntu 18.04 with OpenJDK-8 as the default Python3 interpreter on Ubuntu 18.04 is currently Python 3.6. I've found everything working.

Please investigate your environment further for error, because in normal circumstances e-magyar-tsv works as presented above.
Sorry, but currently we do not offer personal support.

**Comment by dlazesz** [comment]
@recski I'm 100% certain, that `git lfs` was not installed therefore the modelfile is missing.

If it still does not work, please reopen.

**Comment by recski** [comment]
@sassbalint I started over on another server (this one had oracle java), there I got a different exception, originating in emmorphpy, see below. Could be something completely different, did not investigate that one further. Instead, I purged all java installations from the first machine, reinstalled openjdk-8 only, then created a new python environment and reinstalled all dependencies. (note: `WARNING: 'git lfs clone' is deprecated and will not be updated with new flags from 'git clone' `) At this point I got the same error as before (`/usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory`), at which point I checked the JAVA_HOME variable suggested by @dlazesz and it turned out that it was pointing to a now non-existent location. Getting rid of it finally made the test work, since the path hardwired in the code (..openjdk-8...) was now the correct one. 
But it seems then, that one needs either an openjdk-8 installation, or something else that is compatible (openjdk-11 probably isn't) AND an explicitly set JAVA_HOME (which the installation process on Ubuntu does not set, apparently).
My suggestion would be to 1) investigate which java versions are compatible and list them in the README, 2) provide explicit instructions that "JAVA_HOME" must be set to point to a compatible installation, 3) maybe also handle exceptions caused by missing/incorrect libs to provide friendlier error messages.
Thanks for your help!



(sandbox3) recski@student:~/sandbox/e-magyar-tsv$ make RAWINPUT=inputfile test-morph-tag
Traceback (most recent call last):
  File "./emMorphREST.py", line 12, in <module>
    prog = tagger(*args, **kwargs)
  File "/home/recski/sandbox/e-magyar-tsv/emmorphpy/emmorphpy/emmorphpy.py", line 448, in __init__
    self.loaded_conf = list(self._load_config(props))
  File "/home/recski/sandbox/e-magyar-tsv/emmorphpy/emmorphpy/emmorphpy.py", line 76, in _load_config
    props = jprops.load_properties(fp)
  File "/home/recski/.virtualenvs/sandbox3/lib/python3.6/site-packages/jprops.py", line 43, in load_properties
    return mapping(iter_properties(fh))
  File "/home/recski/.virtualenvs/sandbox3/lib/python3.6/site-packages/jprops.py", line 107, in iter_properties
    for line in _property_lines(fh):
  File "/home/recski/.virtualenvs/sandbox3/lib/python3.6/site-packages/jprops.py", line 271, in _property_lines
    for line in _read_lines(fp):
  File "/home/recski/.virtualenvs/sandbox3/lib/python3.6/site-packages/jprops.py", line 263, in _universal_newlines
    for line in lines:
  File "/home/recski/.virtualenvs/sandbox3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 603: ordinal not in range(128)

**Comment by dlazesz** [comment]
@recski Thank you for your cooperation. I've added a FAQ section to README.md with the common errors.
The `UnicodeDecodeError` after loading the JAVA props file is because no Unicode locale is set.

Please run the following and retest:
```
locale-gen hu_HU.UTF-8
update-locale LANG=hu_HU.UTF-8
```
