### ISSUE TITLE
hfst-lookup: Unknown options

### ISSUE THREAD

**Issue by oroszgy** [dlt-rilmta/e-magyar-tsv#2]
Hey guys,

thanks for your awesome work on building this pipeline. I am trying build a Docker image around the stuff, but miserably failed. Do you have any idea, why I am getting this error? 

`hfst-lookup: Unknown options`

Dockerfile:

```
FROM python:3.6-stretch

WORKDIR /app
RUN git clone --recurse-submodules https://github.com/dlt-rilmta/e-magyar-tsv .

RUN apt-get -y update && apt-get -y install openjdk-8-jdk hfst

RUN pip3 install Cython
RUN pip3 install -r emmorphpy/requirements.txt
RUN pip3 install -r purepospy/requirements.txt
RUN pip3 install -r emdeppy/requirements.txt
RUN pip3 install -r HunTag3/requirements.txt

RUN echo "A kutya elment sétálni." > inputfile
CMD ["make", "RAWINPUT=inputfile", "test-morph-tag"]
```

Installed `hfst` versions are below:

```
root@78ee936ba17d:/app# apt-get list | grep hfst

hfst/stable,now 3.10.0~r2798-3 amd64 [installed]
hfst-ospell/stable 0.4.0~r4643-4+b2 amd64
hfst-ospell-dev/stable 0.4.0~r4643-4+b2 amd64
libhfst45/stable,now 3.10.0~r2798-3 amd64 [installed,automatic]
libhfst45-dev/stable 3.10.0~r2798-3 amd64
libhfstospell5/stable 0.4.0~r4643-4+b2 amd64
python-libhfst/stable 3.10.0~r2798-3 amd64
python3-libhfst/stable 3.10.0~r2798-3 amd64
```

**Comment by dlazesz** [comment]
Minimum version of HFST is 3.13.0 as specified in [emMorphPy](https://github.com/ppke-nlpg/emmorphpy) and [emMorph](https://github.com/dlt-rilmta/emMorph).

This is a documentation issue, if it is an issue at all.

**Comment by dlazesz** [comment]
Documentation updated in 7bcf92eb60aaa558e6f7389383160dad71a6f136

**Comment by sassbalint** [comment]
Hi Gyuri,
thank you for your kind words.
Is your problem solved now?

**Comment by oroszgy** [comment]
Hey @dlazesz , thanks for your help, all good now! 🎉 Keep up the good work! 😄
